from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def render_press_clipping_pdf(snapshot: dict[str, Any]) -> bytes:
    """Render a deterministic branded press-clipping PDF from an immutable snapshot."""
    buffer = BytesIO()
    branding = snapshot.get("branding") or {}
    primary = colors.HexColor(branding.get("primary_color") or "#0B3D2E")
    accent = colors.HexColor(branding.get("accent_color") or "#C4A35A")

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=str(snapshot.get("title") or "Press Clipping Report"),
    )
    styles = getSampleStyleSheet()
    brand_style = ParagraphStyle(
        "Brand",
        parent=styles["Heading1"],
        textColor=primary,
        fontSize=20,
        spaceAfter=6,
    )
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading2"],
        textColor=colors.black,
        fontSize=14,
        spaceAfter=10,
    )
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"], fontSize=9, textColor=colors.grey)
    item_title = ParagraphStyle(
        "ItemTitle",
        parent=styles["Heading3"],
        fontSize=11,
        textColor=primary,
        spaceBefore=10,
        spaceAfter=2,
    )
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=12)
    note_style = ParagraphStyle(
        "Note",
        parent=styles["Normal"],
        fontSize=8,
        textColor=accent,
        leftIndent=8,
        spaceBefore=2,
    )

    story: list[Any] = []
    display_name = branding.get("display_name") or snapshot.get("tenant_name") or "NewsFetcher"
    story.append(Paragraph(_escape(str(display_name)), brand_style))
    story.append(Paragraph(_escape(str(snapshot.get("title") or "Press Clipping")), title_style))

    period_start = snapshot.get("period_start") or "—"
    period_end = snapshot.get("period_end") or "—"
    story.append(
        Paragraph(
            f"Period: {_escape(str(period_start))} → {_escape(str(period_end))} &nbsp;|&nbsp; "
            f"Version {snapshot.get('version_number', 1)} &nbsp;|&nbsp; "
            f"Hash {_escape(str(snapshot.get('content_hash', ''))[:16])}",
            meta_style,
        )
    )
    if snapshot.get("notes"):
        story.append(Spacer(1, 6))
        story.append(Paragraph(_escape(str(snapshot["notes"])), body_style))

    story.append(Spacer(1, 8))
    items = [item for item in snapshot.get("items", []) if item.get("included", True)]
    if not items:
        story.append(Paragraph("No included clippings.", body_style))
    for idx, item in enumerate(items, start=1):
        title = item.get("title_snapshot") or "Untitled"
        source = item.get("source_name_snapshot") or "Source"
        story.append(Paragraph(f"{idx}. {_escape(str(title))}", item_title))
        story.append(
            Paragraph(
                f"{_escape(str(source))} — {_escape(str(item.get('url_snapshot') or ''))}",
                meta_style,
            )
        )
        if item.get("snippet_snapshot"):
            story.append(Paragraph(_escape(str(item["snippet_snapshot"])), body_style))
        if item.get("note"):
            story.append(Paragraph(f"Editor note: {_escape(str(item['note']))}", note_style))

    footer = branding.get("footer_text") or "Confidential — generated by NewsFetcher"
    story.append(Spacer(1, 16))
    story.append(Paragraph(_escape(str(footer)), meta_style))

    doc.build(story)
    return buffer.getvalue()


def _escape(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
